### ISSUE TITLE
Implement export/import feature

### ISSUE THREAD

**Issue by sachinjain024** [sachinjain024/stackeye#54]
Here is the source code which could be used to convert text to file and trigger download

```
function getOrCreateDownloadLink() {
    var $link = $('#downloadLink');

    if ($link.length === 0) {
      $link = $('<a id="downloadLink">download</a>').appendTo('body');
    }

    $link.hide();
    return $link;
  }

  function saveAsTextFile(text, fileName) {
    var textFileAsBlob = new Blob([text], { type:'text/plain' }),
      $downloadLink = getOrCreateDownloadLink();

    $downloadLink.attr('download', fileName || 'file');

    if (typeof window.URL !== 'undefined') {
      $downloadLink.attr('href', window.URL.createObjectURL(textFileAsBlob));
    }

    $downloadLink.get(0).click();
  }

  function getOrCreateUploadLink() {
    var $link = $('#uploadLink');

    if ($link.length === 0) {
      $link = $('<input type="file" id="uploadLink" />').appendTo('body');
    }

    $link.hide();
    return $link;
  }

  function loadTextFile(callback) {
    var $link = getOrCreateUploadLink(),
      reader = new FileReader();

    reader.onload = function(evt) {
      callback(evt.target.result);
    };

    $link.change(function() {
      reader.readAsText($link.get(0).files[0], 'UTF-8');
      $link.val('');
    });

    $link.click();
  }
```

**Comment by sachinjain024** [comment]
@seanf I have made some improvements on the top of your pull request. Mainly I improved the interface of exporting, importing and clearing data from storage. Here is how it looks right now,

<img width="803" alt="screenshot 2019-02-12 16 20 35" src="https://user-images.githubusercontent.com/3108399/52630417-351b9f00-2ee2-11e9-94b6-80ab7d25e9a2.png">

Closing this task now. Thanks a lot for helping out with this pull request.

**Comment by seanf** [comment]
Thanks @sachinjain024, that looks great. In future, could I ask you to add your changes on top as separate commits, please? It makes it easier to understand who did what, when. Plus I'm working on other changes built on top of my earlier commits which I might have to rework now.

https://softwareengineering.stackexchange.com/questions/160086/should-a-github-maintainer-rewrite-authors-in-pull-requests/160330

**Comment by sachinjain024** [comment]
Thanks, @seanf for this. You are right and I shouldn't override your commits. I just have a habit of working in a dev/feature branch and then merging the branch into master with `--squash` option to keep the commit history clean. Also, I wasn't aware that you are working on any other change.

Apologies for the mistake and I will be careful next time and avoid using squash.

Thanks once again for the support and great work! Cheers 👍

**Comment by seanf** [comment]
No worries @sachinjain024.
