### ISSUE TITLE
Clicking on Notification is not clearing the notification

### ISSUE THREAD

**Issue by sachinjain024** [sachinjain024/stackeye#56]
<img width="1054" alt="screenshot 2019-02-13 15 08 15" src="https://user-images.githubusercontent.com/3108399/52701850-3233b380-2fa1-11e9-9830-6d5e3cded5a8.png">

This is a regression and got introduced with latest release in v19.2.12

**Comment by sachinjain024** [comment]
Fixed this issue and released v19.2.13. Closing this issue.

**Comment by seanf** [comment]
@sachinjain024 You know, the new TypeScript setup would have caught that (just tried it). :-) You just need to run `npm run watch` (assuming your IDE isn't showing TypeScript errors already).

**Comment by sachinjain024** [comment]
Thanks, Sean for informing this. I will try this out and thanks for
motivating me to look for learning Typescript.
